version = 0.1

[default.deploy.parameters]
stack_name = "sam-s3-file-processor"
resolve_s3 = true
s3_prefix = "sam-s3-file-processor"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
